package com.reserva.backend.common.error;

public enum ErrorCode {
    UNAUTHENTICATED,
    EMAIL_ALREADY_IN_USE,
    FORBIDDEN,
    VALIDATION_ERROR,
    EVENT_NOT_FOUND,
    BOOKING_NOT_FOUND,
    EVENT_SOLD_OUT,
    ALREADY_BOOKED,
    BOOKING_QUANTITY_LIMIT_EXCEEDED,
    INVALID_SCHEDULE
}
